Update curl of isard-webapp
% docker-compose build isard-webapp
Building isard-webapp
Step 1/14 : FROM alpine:3.11.3 as production
 ---> e7d92cdc71fe
Step 2/14 : MAINTAINER isard <info@isard.com>
 ---> Using cache
 ---> 11d6d22f6bc9
Step 3/14 : RUN apk add --no-cache     yarn     py3-paramiko==2.7.1-r0     py3-lxml==4.4.2-r0     py3-openssl==19.1.0-r0     py3-bcrypt==3.1.7-r2     py3-gevent==1.4.0-r2     py3-flask==1.0.4-r0     py3-netaddr==0.7.19-r4     py3-requests==2.22.0-r0         py3-pyldap==3.2.0-r1     curl==7.67.0-r0     openssh-client==8.1_p1-r0     sshpass==1.06-r0     supervisor==4.1.0-r0
 ---> Running in c70e902bc722
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/community/x86_64/APKINDEX.tar.gz
ERROR: unsatisfiable constraints:
  curl-7.67.0-r1:
    breaks: world[curl=7.67.0-r0]
ERROR: Service 'isard-webapp' failed to build: The command '/bin/sh -c apk add --no-cache     yarn     py3-paramiko==2.7.1-r0     py3-lxml==4.4.2-r0     py3-openssl==19.1.0-r0     py3-bcrypt==3.1.7-r2     py3-gevent==1.4.0-r2     py3-flask==1.0.4-r0     py3-netaddr==0.7.19-r4     py3-requests==2.22.0-r0         py3-pyldap==3.2.0-r1     curl==7.67.0-r0     openssh-client==8.1_p1-r0     sshpass==1.06-r0     supervisor==4.1.0-r0' returned a non-zero code: 1