fix(engine): fix update of desktops with QoS
Fix it by not using yattag.indent

2021/10/28 23:35:45 692 - ERROR - changes_domains: Traceback:
 .Traceback (most recent call last):
  File "/isard/engine/controllers/ui_actions.py", line 774, in
      update_hardware_dict_and_xml_from_create_dict
    xml_raw = update_xml_from_dict_domain(id_domain)
  File "/isard/engine/models/domain_xml.py", line 1123, in update_xml_from_dict_domain
    v.randomize_vm()
  File "/isard/engine/models/domain_xml.py", line 972, in randomize_vm
    self.dict_from_xml()
  File "/isard/engine/models/domain_xml.py", line 358, in dict_from_xml
    list_dict['qos'] = xmltodict.parse(bandwidth_xml)['bandwidth']
  File "/usr/lib/python3.8/site-packages/xmltodict.py", line 327, in parse
    parser.Parse(xml_input, True)
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 5, column 1

2021/10/28 23:35:45 693 - ERROR - changes_domains: Exception message: not well-formed
  (invalid token): line 5, column 1